#!/bin/sh

set -e

# Variables that can be provided externally.
: ${CC:=x86_64-unknown-cloudabi-cc}
: ${AR:=x86_64-unknown-cloudabi-ar}
: ${CFLAGS:=-O3 -fstack-protector-strong -fomit-frame-pointer -g}
: ${WARNFLAGS:=}

# Additional compiler flags to include the right files, etc.
CFLAGS="${CFLAGS} -nostdinc -Isrc -Isrc/include \
-Icontrib/double-conversion-1f0b845/src -Icontrib/jemalloc-3.6.0/include \
-Icontrib/openlibm-ef29d06/include -Icontrib/openlibm-ef29d06/src \
-Icontrib/openlibm-ef29d06/ld80 -Icontrib/openlibm-ef29d06 -fno-exceptions \
-fno-rtti -DOPENLIBM_USE_HOST_COMPLEX_H -DOPENLIBM_USE_HOST_FENV_H \
-DOPENLIBM_USE_HOST_MATH_H -DOPENLIBM_ONLY_THREAD_SAFE"

# List of source files.
SRCS=$(find src contrib/double-conversion-1f0b845 contrib/jemalloc-3.6.0 \
    contrib/openlibm-ef29d06 \( -name '*.[cS]' -o -name '*.cc' \) | sort)

echo "=> Computing dependencies"
rm -Rf _obj/dep
mkdir -p _obj/dep
for srcfile in ${SRCS}; do
  safename="$(echo "${srcfile}" | sed -e 's/\//_/g' -e 's/\.[a-zA-Z]*$//')"
  echo "-MT _obj/${safename}.o -MF _obj/dep/${safename}.d ${srcfile}"
done | xargs -P 8 -n 5 ${CC} ${CFLAGS} -MM
for srcfile in ${SRCS}; do
  safename="$(echo "${srcfile}" | sed -e 's/\//_/g' -e 's/\.[a-zA-Z]*$//')"
  case "${srcfile}" in
  contrib/*) extraflags="" ;;
  src/crt/*) extraflags="${WARNFLAGS} -ffreestanding -fno-stack-protector" ;;
  *_test.c) extraflags="${WARNFLAGS} -fno-builtin -O0" ;;
  *) extraflags="${WARNFLAGS}" ;;
  esac
  case "${srcfile}" in
  *.cc) extraflags="${extraflags} -std=c++11" ;;
  esac
  cat >> "_obj/dep/${safename}.d" << EOF
	${CC} ${CFLAGS} ${extraflags} -c -o _obj/${safename}.o ${srcfile}
all: _obj/${safename}.o
EOF
done
cat _obj/dep/*.d > _obj/Makefile

echo "=> Compiling sources"
make -k -j8 -f _obj/Makefile all

echo "=> Linking libraries"
rm -f _obj/libc.a _obj/libm.a _obj/libpthread.a
find src/libc contrib/double-conversion-1f0b845 contrib/jemalloc-3.6.0 \
    contrib/openlibm-ef29d06 \
    \( -name '*.[cS]' -o -name '*.cc' \) \! -name "*_test.c" | sort |
    sed -e 's/\//_/g' -e 's/^/_obj\//' -e 's/\.[a-zA-Z]*$/\.o/' |
    xargs ${AR} -rcs _obj/libc.a
${AR} -rcs _obj/libm.a
${AR} -rcs _obj/libpthread.a
