#!/bin/sh

set -e

: ${PREFIX:=/usr/local/x86_64-unknown-cloudabi}

echo "=> Installing headers"
(cd src/include; find . -type d \! -empty) | while read dir; do
  mkdir -p "${DESTDIR}${PREFIX}/include/${dir}"
done
(cd src/include; find . -type f) | while read file; do
  install -m 444 "src/include/${file}" "${DESTDIR}${PREFIX}/include/${file}"
done
install -m 444 contrib/argdata-0.5/src/argdata.h \
    "${DESTDIR}${PREFIX}/include/"

echo "=> Installing libraries"
mkdir -p "${DESTDIR}${PREFIX}/lib"
install -m 444 _obj/libargdata.a _obj/libc.a _obj/libm.a _obj/libpthread.a \
    _obj/librt.a _obj/libuv.a _obj/libxnet.a \
    _obj/crt0.o _obj/crtbegin.o _obj/crtend.o \
    "${DESTDIR}${PREFIX}/lib/"

echo "=> Installing unit tests"
mkdir -p "${DESTDIR}${PREFIX}/bin"
install -m 555 _obj/cloudlibc-unittests "${DESTDIR}${PREFIX}/bin/"
