#!/bin/sh

set -e

: ${PREFIX:=/usr/local/x86_64-unknown-cloudabi}

echo "=> Installing headers"
(cd src/include; find . -type d \! -empty) | while read dir; do
  mkdir -p "${PREFIX}/include/${dir}"
done
(cd src/include; find . -type f) | while read file; do
  install -m 444 "src/include/${file}" "${PREFIX}/include/${file}"
done

echo "=> Installing libraries"
mkdir -p "${PREFIX}/lib"
install -m 444 _obj/libc.a _obj/libm.a _obj/libpthread.a "${PREFIX}/lib/"
find src/crt -name "*.[cS]" |
    sed -e 's/.*\///' -e 's/\.[a-zA-Z]*$//' | while read crt; do
  install -m 444 _obj/src_crt_${crt}.o "${PREFIX}/lib/${crt}.o"
done
