// Copyright (c) 2015 Nuxi, https://nuxi.nl/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
// OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
// HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
// SUCH DAMAGE.

// <syslog.h> - definitions for system error logging
//
// Extensions:
// - syslog_l() and vsyslog_l():
//   syslog() and vsyslog() always use the C locale.
// - vsyslog():
//   Allows for forwarding of arguments.
//
// Features missing:
// - LOG_PID, LOG_CONS, LOG_NDELAY, LOG_ODELAY, LOG_NOWAIT, openlog() and
//   closelog():
//   Log output is always redirected to stderr.
// - LOG_KERN, LOG_MAIL, LOG_NEWS, LOG_UUCP, LOG_DAEMON, LOG_AUTH, LOG_CRON and
//   LOG_LPR:
//   Log output always uses the LOG_USER facility.

#ifndef _SYSLOG_H_
#define _SYSLOG_H_

#include <_/types.h>

// Logging facilities.
#define LOG_USER 0    // Messages generated by arbitrary processes.
#define LOG_LOCAL0 0  // Reserved for local use.
#define LOG_LOCAL1 0  // Reserved for local use.
#define LOG_LOCAL2 0  // Reserved for local use.
#define LOG_LOCAL3 0  // Reserved for local use.
#define LOG_LOCAL4 0  // Reserved for local use.
#define LOG_LOCAL5 0  // Reserved for local use.
#define LOG_LOCAL6 0  // Reserved for local use.
#define LOG_LOCAL7 0  // Reserved for local use.

#define LOG_MASK(pri) (1 << (pri))

// Logging severities.
#define LOG_DEBUG 0    // A message useful for debugging programs.
#define LOG_INFO 1     // A general information message.
#define LOG_NOTICE 2   // A condition requiring special handling.
#define LOG_WARNING 3  // A warning message.
#define LOG_ERR 4      // An error message.
#define LOG_CRIT 5     // A critical condition.
#define LOG_ALERT 6    // A condition that should be corrected immediately.
#define LOG_EMERG 7    // A panic condition was reported to all processes.

__BEGIN_DECLS
int setlogmask(int);
void syslog(int, const char *, ...);
void syslog_l(int, __locale_t, const char *, ...);
void vsyslog(int, const char *, __va_list);
void vsyslog_l(int, __locale_t, const char *, __va_list);
__END_DECLS

#endif
